version: "3.9"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_DATABASE=cramee
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=mysql://root:secret@mysql:3306/cramee?sslmode=disable
    depends_on:
      - mysql
    entrypoint: ["/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh"]
    command: ["/app/main"]
